rawString = input("please enter a string:")
normalisedString = rawString.strip().lower() 
lenghtOfRawString = len(rawString) 
lenghtOfNormalised = len(normalisedString) 
print(f"That String normalised is :{normalisedString}") 
print(f"we reduced the input string from {lenghtOfRawString} to {lenghtOfNormalised} characters") 
